Repository kubernetes/registry.k8s.io, pull requests merged in 2022-04, with the labels that each got.

#31 Add unit tests
  .github/workflows/archeio-unit-test.yaml
  cmd/archeio/main_test.go
Labels: lgtm, size/L, cncf-cla: yes, approved

#40 Add auto-deploy to CloudRun regions
  Makefile
  cloudbuild.yaml
  hack/make-rules/deploy.sh
Labels: lgtm, cncf-cla: yes, size/M, approved

#43 enable staticcheck in go1.18
  hack/tools/go.mod
  hack/tools/go.sum
Labels: lgtm, cncf-cla: yes, size/M, approved

#44 update go to 1.18.1
  .go-version
Labels: lgtm, size/XS, cncf-cla: yes, approved

#42 implement CIDR matching
  hack/tools/.golangci.yml
  pkg/net/cidrs/aws/doc.go
  pkg/net/cidrs/aws/internal/ranges2go/gen.go
  pkg/net/cidrs/aws/internal/ranges2go/genrawdata.sh
  pkg/net/cidrs/aws/internal/ranges2go/main.go
  pkg/net/cidrs/aws/internal/ranges2go/parse.go
  pkg/net/cidrs/aws/internal/ranges2go/run.sh
  pkg/net/cidrs/aws/internal/ranges2go/zz_generated_rawdata.go
  pkg/net/cidrs/aws/mapper.go
  pkg/net/cidrs/aws/mapper_test.go
  pkg/net/cidrs/aws/zz_generated_range_data.go
  pkg/net/cidrs/bruteforce.go
  pkg/net/cidrs/bruteforce_test.go
  pkg/net/cidrs/ipmapper.go
  pkg/net/cidrs/testdatacommon_test.go
  pkg/net/cidrs/triemap.go
  pkg/net/cidrs/triemap_test.go
Labels: size/XXL, lgtm, cncf-cla: yes, approved

#46 add missing copyright header
  cmd/archeio/main_test.go
Labels: size/S, lgtm, cncf-cla: yes, approved

#48 add some more details to README.md
  cmd/archeio/README.md
Labels: lgtm, cncf-cla: yes, size/M, approved

#49 Redirect to a placeholder URL about this service
  cmd/archeio/app/handlers.go
Labels: lgtm, size/XS, cncf-cla: yes, approved

#50 increase pkg/net/cidrs unit test coverage to 100%
  pkg/net/cidrs/triemap.go
  pkg/net/cidrs/triemap_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#51 test case for root url redirection
  cmd/archeio/app/handlers_test.go
Labels: lgtm, size/XS, cncf-cla: yes, approved

#53 drive up test coverage, drop redundant integration test skip
  cmd/archeio/main_test.go
  hack/make-rules/test.sh
  internal/integration/doc.go
  internal/integration/skip.go
  pkg/net/cidrs/aws/internal/ranges2go/gen_test.go
  pkg/net/cidrs/aws/internal/ranges2go/main.go
  pkg/net/cidrs/aws/internal/ranges2go/parse.go
  pkg/net/cidrs/aws/internal/ranges2go/parse_test.go
Labels: lgtm, size/L, cncf-cla: yes, approved

#54 Remove shellcheck comment
  hack/make-rules/deploy.sh
Labels: lgtm, size/XS, cncf-cla: yes, approved

#56 fix bugs in GetClientIP and MakeHandlers
  cmd/archeio/app/clientip.go
  cmd/archeio/app/clientip_test.go
  cmd/archeio/app/handlers.go
Labels: lgtm, size/XS, cncf-cla: yes, approved

#57 delete unused github action
  .github/workflows/archeio-unit-test.yaml
Labels: size/S, lgtm, cncf-cla: yes, approved

#60 improve logging
  cmd/archeio/app/handlers.go
  hack/make-rules/deploy.sh
Labels: lgtm, size/XS, cncf-cla: yes, approved

#61 REVERT ME: debug why we're not redirecting kops to S3
  cmd/archeio/app/handlers.go
Labels: lgtm, size/XS, cncf-cla: yes, approved

#64 add cloud run bug quirks-mode to getClientIP
  cmd/archeio/app/clientip.go
  cmd/archeio/app/clientip_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#65 Revert "REVERT ME: debug why we're not redirecting kops to S3"
  cmd/archeio/app/handlers.go
Labels: lgtm, size/XS, cncf-cla: yes, approved

#66 HEAD check and fallback if S3 is missing layers
  cmd/archeio/app/buckets.go
  cmd/archeio/app/buckets_integration_test.go
  cmd/archeio/app/buckets_test.go
  cmd/archeio/app/handlers.go
  cmd/archeio/app/handlers_test.go
Labels: lgtm, size/L, cncf-cla: yes, approved

#67 cache bucket HEAD requests
  cmd/archeio/app/buckets.go
  cmd/archeio/app/buckets_integration_test.go
  cmd/archeio/app/handlers.go
  cmd/archeio/app/handlers_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#68 log cache hits
  cmd/archeio/app/buckets.go
  hack/make-rules/deploy.sh
Labels: lgtm, size/XS, cncf-cla: yes, approved
