Repository kubernetes/registry.k8s.io, pull requests merged in 2022-12, with the labels that each got.

#135 go1.19.4
  .go-version
Labels: lgtm, size/XS, cncf-cla: yes, approved

#132 clientip: Add tests for IPv6
  pkg/clientip/clientip.go
  pkg/clientip/clientip_test.go
Labels: size/S, lgtm, cncf-cla: yes, approved

#133 chore: update aws ip address ranges
  pkg/net/cidrs/aws/internal/ranges2go/zz_generated_rawdata.go
  pkg/net/cidrs/aws/zz_generated_range_data.go
Labels: ok-to-test, size/XXL, lgtm, cncf-cla: yes, approved
