Repository kubernetes/registry.k8s.io, pull requests merged in 2022-10, with the labels that each got.

#110 set container conurrency and GOMAXPROCS
  hack/make-rules/deploy.sh
Labels: lgtm, size/XS, cncf-cla: yes, approved

#112 Use artifact registry for sandbox
  hack/make-rules/deploy.sh
Labels: lgtm, size/XS, cncf-cla: yes, approved

#113 fix deploy parameter script
  hack/make-rules/deploy.sh
Labels: lgtm, size/XS, cncf-cla: yes, approved

#114 add some background details, and a note about privacy.
  README.md
Labels: size/S, lgtm, cncf-cla: yes, approved

#117 update default URLs
  cmd/archeio/main.go
Labels: lgtm, size/XS, cncf-cla: yes, approved

#118 map to nearest AWS regions as previously proposed
  cmd/archeio/app/buckets.go
  cmd/archeio/app/buckets_test.go
  cmd/archeio/app/handlers_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#119 drop cloud run bug handling, as the bug has been fixed since july
  cmd/archeio/app/clientip.go
  cmd/archeio/app/clientip_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#120 remove s3 featuregate
  cmd/archeio/app/handlers.go
  cmd/archeio/app/handlers_test.go
  cmd/archeio/main.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#121 simplify redirect path calculation
  cmd/archeio/app/handlers.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#123 add a note re: intention for reusability
  cmd/archeio/README.md
Labels: lgtm, size/XS, cncf-cla: yes, approved

#124 set expectations clearly
  README.md
Labels: size/S, lgtm, cncf-cla: yes, approved
