Repository kubernetes/registry.k8s.io, pull requests merged in 2022-09, with the labels that each got.

#99 update ip addresses
  pkg/net/cidrs/aws/internal/ranges2go/genrawdata.sh
  pkg/net/cidrs/aws/internal/ranges2go/run.sh
  pkg/net/cidrs/aws/internal/ranges2go/zz_generated_rawdata.go
  pkg/net/cidrs/aws/zz_generated_range_data.go
Labels: size/XXL, lgtm, cncf-cla: yes, approved

#100 update to go 1.19.1
  .go-version
  cmd/archeio/main_test.go
  pkg/net/cidrs/triemap.go
Labels: lgtm, size/XS, cncf-cla: yes, approved

#101 Fix GCP regions
  hack/make-rules/deploy.sh
Labels: lgtm, size/XS, cncf-cla: yes, approved

#102 Bump klog to latest
  go.mod
  go.sum
Labels: lgtm, size/XS, cncf-cla: yes, approved

#104 Update readme description
  README.md
Labels: lgtm, size/XS, cncf-cla: yes, approved

#107 rename sigs.k8s.io/oci-proxy => k8s.io/registry.k8s.io
  README.md
  cmd/archeio/app/buckets_test.go
  cmd/archeio/app/handlers.go
  cmd/archeio/main.go
  cmd/archeio/main_test.go
  go.mod
  hack/make-rules/test.sh
  hack/tools/go.mod
  pkg/net/cidrs/aws/mapper.go
  pkg/net/cidrs/aws/mapper_test.go
Labels: size/S, lgtm, cncf-cla: yes, approved

#108 update tools dependencies
  go.mod
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/XXL, lgtm, cncf-cla: yes, approved

#109 Add more regions for sandbox environments
  hack/make-rules/deploy.sh
Labels: lgtm, size/XS, cncf-cla: yes, approved
