Repository kubernetes/registry.k8s.io, pull requests merged in 2022-03, with the labels that each got.

#18 Add custom registries for e2e tests.
  hack/images/default-sandbox.yaml
Labels: lgtm, size/XS, cncf-cla: yes, approved

#21 Slowloris and graceful shutdown
  cmd/archeio/main.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#28 support overriding upstream
  cmd/archeio/main.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#30 hack: update golangci-lint
  hack/tools/.golangci.yml
  hack/tools/go.mod
  hack/tools/go.sum
Labels: lgtm, size/L, cncf-cla: yes, approved

#33 hack: bump ko to 0.11.2
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/XXL, lgtm, cncf-cla: yes, approved

#35 drop v1 support
  cmd/archeio/main.go
Labels: size/S, lgtm, cncf-cla: yes, approved

#36 upgrade to go1.18
  .go-version
  go.mod
Labels: lgtm, size/XS, cncf-cla: yes, approved
