Repository kubernetes/registry.k8s.io, pull requests merged in 2022-01, with the labels that each got.

#1 Add bentheelder, hh, riaankl, and myself to OWNERS
  OWNERS
Labels: lgtm, size/XS, cncf-cla: yes, approved

#3 Fix typo for reviewers in OWNERS file
  OWNERS
Labels: lgtm, size/XS, cncf-cla: yes, approved

#4 OWNERS: add bentheelder as approver
  OWNERS
Labels: lgtm, size/XS, cncf-cla: yes, approved

#5 initial redirector service implementation
  .gitignore
  .go-version
  Dockerfile
  Makefile
  cmd/archeio/README.md
  cmd/archeio/main.go
  go.mod
  hack/make-rules/gofmt.sh
  hack/make-rules/images.sh
  hack/make-rules/lint.sh
  hack/make-rules/shellcheck.sh
  hack/make-rules/test.sh
  hack/make-rules/tidy.sh
  hack/make-rules/update.sh
  hack/make-rules/verify.sh
  hack/third_party/gimme/LICENSE
  hack/third_party/gimme/README.md
  hack/third_party/gimme/gimme
  hack/tools/.golangci.yml
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/setup-go.sh
  hack/tools/tools.go
Labels: size/XXL, lgtm, cncf-cla: yes, approved

#6 Cleanup
  Dockerfile
  cmd/archeio/main.go
Labels: lgtm, size/XS, cncf-cla: yes, approved

#9 make image publishable with automatic date-sha tag
  Makefile
  cloudbuild.yaml
  hack/make-rules/images.sh
Labels: lgtm, cncf-cla: yes, size/M, approved

#11 fixes for enabling CI
  hack/make-rules/images.sh
  hack/make-rules/verify.sh
  hack/tools/ci-install-shellcheck.sh
Labels: lgtm, cncf-cla: yes, size/M, approved

#10 cleanup boilerplate files slightly
  README.md
  RELEASE.md
  SECURITY_CONTACTS
Labels: size/S, lgtm, cncf-cla: yes, approved

#12 update maliinglist
  README.md
Labels: lgtm, size/XS, cncf-cla: yes, approved
