Repository kubernetes/registry.k8s.io, pull requests merged in 2022-07, with the labels that each got.

#84 Return temporary redirects instead of permanent ones
  cmd/archeio/app/handlers.go
  cmd/archeio/app/handlers_test.go
Labels: size/S, lgtm, cncf-cla: yes, approved

#86 Add endpoint to serve LF privacy page
  cmd/archeio/app/handlers.go
  cmd/archeio/app/handlers_test.go
  cmd/archeio/docs/request-handling.md
Labels: ok-to-test, size/S, lgtm, cncf-cla: yes, approved

#85 update the / redirection
  cmd/archeio/app/handlers.go
Labels: ok-to-test, lgtm, size/XS, cncf-cla: yes, approved

#82 Update AWS region to S3 url to use production buckets
  cmd/archeio/app/buckets.go
  cmd/archeio/app/handlers_test.go
Labels: size/S, lgtm, cncf-cla: yes, approved

#88 Feature gate serving AWS S3 blobs from oci-proxy
  cmd/archeio/app/handlers.go
  cmd/archeio/app/handlers_test.go
  cmd/archeio/main.go
Labels: lgtm, size/L, cncf-cla: yes, approved

#92 Fix infoURL
  cmd/archeio/main.go
Labels: lgtm, size/XS, cncf-cla: yes, approved
