Repository kubernetes/registry.k8s.io, pull requests merged in 2023-02, with the labels that each got.

#147 Default to AWS when possible
  cmd/archeio/app/buckets.go
  cmd/archeio/app/buckets_integration_test.go
  cmd/archeio/app/buckets_test.go
  cmd/archeio/app/handlers.go
  cmd/archeio/docs/request-handling.md
  cmd/archeio/main.go
  hack/make-rules/verify-generated.sh
  pkg/net/cidrs/aws/internal/ranges2go/genrawdata.sh
  pkg/net/cloudcidrs/doc.go
  pkg/net/cloudcidrs/internal/ranges2go/data/aws-ip-ranges.json
  pkg/net/cloudcidrs/internal/ranges2go/data/gcp-cloud.json
  pkg/net/cloudcidrs/internal/ranges2go/gen.go
  pkg/net/cloudcidrs/internal/ranges2go/gen_test.go
  pkg/net/cloudcidrs/internal/ranges2go/main.go
  pkg/net/cloudcidrs/internal/ranges2go/parse_aws.go
  pkg/net/cloudcidrs/internal/ranges2go/parse_aws_test.go
  pkg/net/cloudcidrs/internal/ranges2go/parse_gcp.go
  pkg/net/cloudcidrs/internal/ranges2go/parse_gcp_test.go
  pkg/net/cloudcidrs/internal/ranges2go/prefix_helpers.go
  pkg/net/cloudcidrs/internal/ranges2go/regionstoprefixes.go
  pkg/net/cloudcidrs/internal/ranges2go/run.sh
  pkg/net/cloudcidrs/internal/ranges2go/update-data.sh
  pkg/net/cloudcidrs/ipinfo.go
  pkg/net/cloudcidrs/ipmapper.go
  pkg/net/cloudcidrs/ipmapper_test.go
  pkg/net/cloudcidrs/zz_generated_range_data.go
Labels: size/XXL, lgtm, cncf-cla: yes, approved

#149 clarify stability documentation, link to blogpost
  README.md
Labels: size/S, lgtm, cncf-cla: yes, approved

#150 update tools to latest
  hack/tools/.golangci.yml
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/XXL, lgtm, cncf-cla: yes, approved

#146 Copy sync script over and use the bucket backing `gcr.io/k8s-artifacts-prod`
  hack/tools/sync-to-s3.sh
Labels: lgtm, cncf-cla: yes, size/M, approved

#151 MVP: "geranos" GCR/AR to S3 sync tool
  cmd/geranos/README.md
  cmd/geranos/main.go
  cmd/geranos/s3uploader.go
  cmd/geranos/schemav1.go
  cmd/geranos/walkimages.go
  go.mod
  go.sum
Labels: lgtm, size/XL, cncf-cla: yes, approved

#156 Remove BobyMCbobs from reviewers
  OWNERS
Labels: lgtm, size/XS, cncf-cla: yes, approved

#159 k8s-infra: change file mode bits for sync script
  hack/tools/sync-to-s3.sh
Labels: lgtm, size/XS, cncf-cla: yes, approved

#155 iterate on geranos MVP
  cmd/geranos/main.go
  cmd/geranos/s3uploader.go
  cmd/geranos/walkimages.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#160 add a progress logging TODO and move layer logging to higher verbosity
  cmd/geranos/main.go
  cmd/geranos/s3uploader.go
Labels: lgtm, size/XS, cncf-cla: yes, approved
