Repository kubernetes/registry.k8s.io, pull requests merged in 2023-03, with the labels that each got.

#161 don't upload config layers for now
  cmd/geranos/walkimages.go
Labels: size/S, lgtm, cncf-cla: yes, approved

#163 reduce geranos concurrency
  cmd/geranos/walkimages.go
Labels: lgtm, size/XS, cncf-cla: yes, approved

#165 rate limit most AR calls
  cmd/geranos/s3uploader.go
  cmd/geranos/walkimages.go
  go.mod
  go.sum
Labels: size/S, lgtm, cncf-cla: yes, approved

#166 rate limit all AR API calls
  cmd/geranos/main.go
  cmd/geranos/ratelimitroundtrip.go
  cmd/geranos/s3uploader.go
  cmd/geranos/schemav1.go
  cmd/geranos/walkimages.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#167 Docs updates
  README.md
  cmd/archeio/README.md
Labels: lgtm, size/XS, cncf-cla: yes, approved

#164 reject requests for /v2/_catalog
  cmd/archeio/app/handlers.go
  cmd/archeio/app/handlers_test.go
Labels: size/S, lgtm, cncf-cla: yes, approved

#170 increase geranos registry rate limit
  cmd/geranos/main.go
Labels: lgtm, size/XS, cncf-cla: yes, approved

#173 archeio: support blob digest algorithms other than sha256
  cmd/archeio/app/handlers.go
  cmd/archeio/app/handlers_test.go
  cmd/geranos/s3uploader.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#175 clarify archeio docs
  cmd/archeio/README.md
  cmd/archeio/docs/request-handling.md
Labels: lgtm, cncf-cla: yes, size/M, approved

#177 Fix archeio stability link
  cmd/archeio/README.md
Labels: ok-to-test, lgtm, size/XS, cncf-cla: yes, approved

#176 Update ko version
  hack/tools/go.mod
  hack/tools/go.sum
Labels: lgtm, size/L, cncf-cla: yes, approved, needs-ok-to-test

#178 fix dependabot alerts
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/S, lgtm, cncf-cla: yes, approved

#179 enforce code coverage levels
  cmd/archeio/docs/testing.md
  hack/make-rules/test.sh
  hack/tools/require-coverage/main.go
  pkg/net/cloudcidrs/internal/ranges2go/gen_test.go
  pkg/net/cloudcidrs/internal/ranges2go/parse_gcp_test.go
Labels: lgtm, size/L, cncf-cla: yes, approved

#180 simplify ratelimitroundtripper
  cmd/geranos/main.go
  cmd/geranos/ratelimitroundtrip.go
Labels: lgtm, size/XS, cncf-cla: yes, approved

#183 Add debugging issues with registry.k8s.io document
  debugging.md
Labels: ok-to-test, lgtm, size/L, cncf-cla: yes, approved

#184 Minor debugging document fixes
  docs/debugging.md
Labels: ok-to-test, lgtm, size/XS, cncf-cla: yes, approved

#185 Add issue template
  .github/ISSUE_TEMPLATE/issue.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved

#186 add running crane remotely instructions
  docs/debugging.md
Labels: lgtm, cncf-cla: yes, size/M, approved

#189 docs cleanup and start mirroring guides
  README.md
  docs/mirroring/README.md
  docs/mirroring/containerd.md
  docs/mirroring/kubeadm.md
Labels: lgtm, size/L, cncf-cla: yes, approved

#190 Add oras mirror instructions
  docs/mirroring/README.md
Labels: ok-to-test, lgtm, size/XS, cncf-cla: yes, approved

#191 Mirroring nits
  README.md
  docs/mirroring/README.md
Labels: size/S, lgtm, cncf-cla: yes, approved

#192 Add Harbor proxy cache instructions
  docs/mirroring/README.md
Labels: ok-to-test, size/S, lgtm, cncf-cla: yes, approved

#193 refresh archeio docs to current details
  cmd/archeio/README.md
Labels: size/S, lgtm, cncf-cla: yes, approved

#200 use community images to list images to mirror
  docs/mirroring/README.md
Labels: lgtm, cncf-cla: yes, size/M, approved

#201 expand kOps and containerd mirroring guides
  docs/mirroring/README.md
  docs/mirroring/containerd.md
  docs/mirroring/kOps.md
Labels: lgtm, cncf-cla: yes, size/M, approved

#202 mirroring nit
  docs/mirroring/README.md
Labels: lgtm, size/XS, cncf-cla: yes, approved

#203 add cri-o mirroring guide
  docs/mirroring/README.md
  docs/mirroring/containerd.md
  docs/mirroring/cri-o.md
Labels: lgtm, cncf-cla: yes, size/M, approved

#204 add cri-dockerd mirroring guide
  docs/mirroring/README.md
  docs/mirroring/cri-dockerd.md
Labels: lgtm, cncf-cla: yes, size/M, approved

#205 add links to skip ahead below each mirroring option
  docs/mirroring/README.md
Labels: size/S, lgtm, cncf-cla: yes, approved

#207 upgrade to go 1.19.7
  .go-version
Labels: lgtm, size/XS, cncf-cla: yes, approved

#206 stop exporting archeio internals
  cmd/archeio/internal/app/buckets.go
  cmd/archeio/internal/app/buckets_integration_test.go
  cmd/archeio/internal/app/buckets_test.go
  cmd/archeio/internal/app/handlers.go
  cmd/archeio/internal/app/handlers_test.go
  cmd/archeio/main.go
Labels: lgtm, size/XS, cncf-cla: yes, approved

#209 geranos: enable uploading config layers
  cmd/geranos/walkimages.go
Labels: size/S, lgtm, cncf-cla: yes, approved

#212 add a debugging hint for GCP block
  docs/debugging.md
Labels: size/S, lgtm, cncf-cla: yes, approved

#213 mirroring instructions for Cluster API
  docs/mirroring/README.md
  docs/mirroring/cluster-api.md
Labels: size/S, lgtm, cncf-cla: yes, approved
