Repository kubernetes/registry.k8s.io, pull requests merged in 2023-05, with the labels that each got.

#239 drop eu-west-2 bucket
  cmd/archeio/internal/app/buckets.go
  cmd/archeio/internal/app/handlers_test.go
Labels: size/S, lgtm, cncf-cla: yes, approved

#241 test that all configured buckets serve a sample blob
  cmd/archeio/internal/app/buckets_integration_test.go
  pkg/net/cloudcidrs/ipmapper.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#240 Add Hippie Hacker to SECURITY_CONTACTS
  SECURITY_CONTACTS
Labels: lgtm, size/XS, cncf-cla: yes, approved

#242 move clientip package under pkg/net for consistency
  cmd/archeio/internal/app/handlers.go
  pkg/net/clientip/clientip.go
  pkg/net/clientip/clientip_test.go
Labels: lgtm, size/XS, cncf-cla: yes, approved

#243 cleanup effectively external AWS region mapping
  cmd/archeio/internal/app/buckets.go
  cmd/archeio/internal/app/buckets_test.go
Labels: size/S, lgtm, cncf-cla: yes, approved

#244 cleanup experiment
  experiment/MANUALLY_SYNCING_BUCKETS.md
  experiment/OWNERS
  experiment/README.md
  experiment/hack/initial-copy-between-s3.sh
  experiment/hack/initial-copy-to-s3.sh
  experiment/registry-k8s-io-account-structure.dot
  experiment/registry-k8s-io-account-structure.svg
Labels: lgtm, size/L, sig/release, cncf-cla: yes, approved

#248 geranos: skip already uploaded images
  cmd/geranos/main.go
  cmd/geranos/s3uploader.go
  cmd/geranos/walkimages.go
Labels: lgtm, size/L, cncf-cla: yes, approved

#249 nit: shared log message
  cmd/geranos/s3uploader.go
Labels: lgtm, size/XS, cncf-cla: yes, approved

#251 add make target to build geranos
  Makefile
Labels: size/S, lgtm, cncf-cla: yes, approved

#252 geranos: return err and don't double log "Done!"
  cmd/geranos/main.go
Labels: lgtm, size/XS, cncf-cla: yes, approved
